apiVersion: v1
kind: Pod
metadata:
  name: dsa-accel-config-demo
  labels:
    app: dsa-accel-config-demo
spec:
  containers:
  - name: dsa-accel-config-demo
    image: intel/accel-config-demo:0.26.2
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        dsa.intel.com/wq-user-dedicated: 1
        # In kernels 5.13-5.17, ENQCMD is disabled (is to be reinstated in 5.18)
        # dsa.intel.com/wq-user-shared: 1
  restartPolicy: Never
