apiVersion: v1
kind: Pod
metadata:
  name: iaa-accel-config-demo
  labels:
    app: iaa-accel-config-demo
spec:
  containers:
  - name: iaa-accel-config-demo
    image: intel/accel-config-demo:0.28.0
    command: [ "/bin/bash", "-c", "cd /test && /bin/bash -e ./iaa_user_test_runner.sh" ]
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        iaa.intel.com/wq-user-dedicated: 1
        # In kernels 5.13-5.17, ENQCMD is disabled (is to be reinstated in 5.18)
        # iaa.intel.com/wq-user-shared: 1
  restartPolicy: Never
